### ISSUE TITLE
Create a Roadmap

### ISSUE THREAD

**Issue by Pyxxil** [Pyxxil/Blackhole#222]
There should be a roadmap somewhere of where the project wants to go, and what it will offer over other established projects.

The roadmap at time of writing looks like this:

## Roadmap

- [ ] Client
  - [ ] View all blocklists
  - [ ] Check that blocklist domain isn't blocked
  - [ ] Check what list(s) blocked a domain
  - [ ] Ability to check overlap of blocklists
- [ ] Server
  - [ ] Prometheus Export
  - [ ] Open Telemetry
  - [ ] Health Endpoint
